// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';

export const LOGIN_ADMIN_REQUEST = 'LOGIN_ADMIN_REQUEST';
export const LOGIN_ADMIN_RESPONSE = 'LOGIN_ADMIN_REQUEST';

export const SET_ADMIN_CREDENTIALS = 'SET_ADMIN_CREDENTIALS';

export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOG_OUT';
//register
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_RESPONSE = 'REGISTER_RESPONSE';

//loaders
export const LOADING_ENABLE_LOADER = 'LOADING_ENABLE_LOADER';
export const LOADING_DISABLE_LOADER = 'LOADING_DISABLE_LOADER';
//TOAST
export const ENABLE_SNACKBAR = 'ENABLE_SNACKBAR';
export const DISABLE_SNACKBAR = 'DISABLE_SNACKBAR';
//News
export const All_NEWS_REQUEST = 'All_NEWS_REQUEST';
export const All_NEWS_RESPONSE = 'All_NEWS_RESPONSE';
//CatEGORY
export const GET_CONFIG_REQUEST = 'GET_CONFIG_REQUEST';
export const GET_CONFIG_RESPONSE = 'GET_CONFIG_RESPONSE';
//
export const GET_CATEGORY_NEWS_REQUEST = 'GET_CATEGORY_NEWS_REQUEST';
export const GET_CATEGORY_NEWS_RESPONSE = 'GET_CATEGORY_NEWS_RESPONSE';
//
export const SAVE_NEWS_RESPONSE = 'SAVE_NEWS_RESPONSE';
export const UNSAVE_NEWS_RESPONSE = 'UNSAVE_NEWS_RESPONSE';

//
export const ENABLE_REFRESHING = 'ENABLE_REFRESHING';
export const DISABLE_REFRESHING = 'DISABLE_REFRESHING';

export const ON_NOTIFICATION = 'IS_NOTIFICATION';
export const OFF_NOTIFICATION = 'OFF_NOTIFICATION';

export const ENABLE_NIGHT_MODE = 'ENABLE_NIGHT_MODE';
export const DISABLE_NIGHT_MODE = 'DISABLE_NIGHT_MODE';

export const MANUAL_ENABLE_NIGHT_MODE = 'MANUAL_ENABLE_NIGHT_MODE';
export const MANUAL_DISABLE_NIGHT_MODE = 'MANUAL_DISABLE_NIGHT_MODE';

export const ON_PRESS_NEWS_DETAIL = 'ON_PRESS_NEWS_DETAIL';
export const ON_EXPAND_DETAIL = 'ON_EXPAND_DETAIL';

export const ON_RATE = 'ON_RATE';
